# Introduction

After the meeting of 28/04/2021, we decided to split the PRIMAP-HIST dataset (with extrapolation) into 2 datasets depending on the 2 different scenarios.

The first one will contain all the data with the HISTCR scenario and the other, the HISTTP scenario.

# Dataset loading

In [13]:
import pandas as pd

folder = "../../../data/ghg-emissions/primap-hist/"
dataset_name = "PRIMAP-hist_v2.2_19-Jan-2021.csv"
primap_hist_data = pd.read_csv(folder+dataset_name)

In [14]:
primap_hist_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28622 entries, 0 to 28621
Columns: 174 entries, scenario to 2018
dtypes: float64(169), object(5)
memory usage: 38.0+ MB

# Dataset splitting

Getting all the HISTCR scenario data.

In [15]:
primap_histcr_data = primap_hist_data[primap_hist_data.scenario == "HISTCR"]
primap_histcr_data.shape

(14311, 174)

In [16]:
primap_histcr_data.head()

,scenario,country,category,entity,unit,1850,1851,1852,1853,1854,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,HISTCR,ABW,IPC1A,CH4,Gg,0.000153,0.000158,0.000164,0.000169,0.000174,...,0.03550,0.0385,0.03170,0.05170,0.06840,0.05940,0.05950,0.05390,0.05520,0.0565
1,HISTCR,AFG,IPC1A,CH4,Gg,0.023700,0.023800,0.023900,0.024100,0.024200,...,4.07000,4.4900,5.22000,7.82000,11.70000,5.42000,5.38000,7.59000,7.96000,8.3300
2,HISTCR,AGO,IPC1A,CH4,Gg,1.750000,1.770000,1.800000,1.820000,1.840000,...,57.70000,59.1000,60.50000,61.70000,63.00000,64.30000,65.60000,66.90000,68.30000,69.6000
3,HISTCR,AIA,IPC1A,CH4,Gg,0.000010,0.000010,0.000010,0.000010,0.000010,...,0.00205,0.0024,0.00256,0.00256,0.00275,0.00275,0.00276,0.00286,0.00298,0.0031
4,HISTCR,ALB,IPC1A,CH4,Gg,0.060200,0.060600,0.061500,0.063100,0.065200,...,5.14000,5.0400,4.98000,4.87000,4.79000,4.66000,4.89000,5.00000,5.02000,5.0400

In [17]:
primap_histtp_data = primap_hist_data[primap_hist_data.scenario == "HISTTP"]
primap_histtp_data.shape

(14311, 174)

In [18]:
primap_histtp_data.head()

,scenario,country,category,entity,unit,1850,1851,1852,1853,1854,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
14311,HISTTP,ABW,IPC1A,CH4,Gg,0.000153,0.000158,0.000164,0.000169,0.000174,...,0.03550,0.0385,0.03170,0.05170,0.06840,0.05940,0.05950,0.05390,0.05520,0.0565
14312,HISTTP,AFG,IPC1A,CH4,Gg,0.023700,0.023800,0.023900,0.024100,0.024200,...,4.07000,4.4900,5.22000,7.82000,11.70000,5.42000,5.38000,7.59000,7.96000,8.3300
14313,HISTTP,AGO,IPC1A,CH4,Gg,1.750000,1.770000,1.800000,1.820000,1.840000,...,57.70000,59.1000,60.50000,61.70000,63.00000,64.30000,65.60000,66.90000,68.30000,69.6000
14314,HISTTP,AIA,IPC1A,CH4,Gg,0.000010,0.000010,0.000010,0.000010,0.000010,...,0.00205,0.0024,0.00256,0.00256,0.00275,0.00275,0.00276,0.00286,0.00298,0.0031
14315,HISTTP,ALB,IPC1A,CH4,Gg,0.079500,0.079900,0.081200,0.083200,0.086100,...,2.89000,2.8300,2.79000,2.73000,2.69000,2.61000,2.74000,2.65000,2.62000,2.5900

# Datasets exports

In [19]:
primap_histcr_data.to_csv(folder+'PRIMAP-HISTCR.csv')

In [20]:
primap_histtp_data.to_csv(folder+'PRIMAP-HISTTP.csv')